## Perceptron

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
plt.style.use("fivethirtyeight")

In [31]:
class Perceptron:
    def __init__ (self, eta, epochs):   ##epochs:iterations
        self.weights=np.random.randn(3) * 1e-4
        print (f'self.weights: {self.weights}')
        self.eta=eta
        self.epochs=epochs
    def activationfunction(self,inputs,weights):
        z=np.dot(inputs,weights)
        return np.where(z>0,1,0)
    def fit(self,X,y):
        self.X=X
        self.y=y
        X_with_bias=np.c_[self.X,-np.ones((len(self.X),1))]
        print(f'X_with_bias:\n{X_with_bias}')
    
        for epoch in range(self.epochs):
            print(f"for epoch: {epoch}")
            y_hat = self.activationfunction(X_with_bias, self.weights)
            print(f"predicted value: \n{y_hat}")
            error = self.y - y_hat
            print(f"error: \n{error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
            print(f"updated weights: \n{self.weights}")
            print("#############\n")

    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
        return self.activationfunction(X_with_bias, self.weights)

In [32]:
data={'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,0,0,1]}
AND=pd.DataFrame(data)

In [33]:
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [34]:
X=AND.drop('y',axis=1)

In [35]:
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [36]:
y=AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [37]:
model=Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights: [ 1.18271393e-04 -4.72970758e-05  9.60262102e-05]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value:
[0 0 1 0]
error:
0    0
1    0
2   -1
3    1
Name: y, dtype: int64
updated weights:
[1.18271393e-04 4.99952703e-01 9.60262102e-05]
#############

for epoch: 1
predicted value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-4.99881729e-01 -4.72970758e-05  1.00009603e+00]
#############

for epoch: 2
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[1.18271393e-04 4.99952703e-01 5.00096026e-01]
#############

for epoch: 3
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[5.00118271e-01 9.99952703e-01 9.60262102e-05]
#############

for epoch: 4
predicted value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[1.18271393e-04 4.99952703e-01 1.00009603e+00]
#############

for epoch: 5
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.50011827 0.9999527  0.50009603]
#############

for epoch: 6
predicted value:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[1.18271393e-04 4.99952703e-01 1.50009603e+00]
#############

for epoch: 7
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.50011827 0.9999527  1.00009603]
#############

for epoch: 8
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.50011827 0.9999527  1.00009603]
#############

for epoch: 9
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.50011827 0.9999527  1.00009603]
#############

In [38]:
model.predict(X)

array([0, 0, 0, 1])

In [53]:
data1={'x1':[0,0,1,1],'x2':[0,1,0,1],'y':[0,1,1,1]}
OR=pd.DataFrame(data1)

In [54]:
OR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [55]:
X=OR.drop('y',axis=1)

In [56]:
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [57]:
y=OR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  1

In [59]:
model=Perceptron(eta=0.5,epochs=10)
model.fit(X,y)

self.weights: [ 5.58866327e-05 -2.94346259e-05  1.96035023e-05]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value:
[0 0 1 1]
error:
0    0
1    1
2    0
3    0
Name: y, dtype: int64
updated weights:
[ 5.58866327e-05  4.99970565e-01 -4.99980396e-01]
#############

for epoch: 1
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

for epoch: 2
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

for epoch: 3
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

for epoch: 4
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

for epoch: 5
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

for epoch: 6
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

for epoch: 7
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

for epoch: 8
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

for epoch: 9
predicted value:
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[5.58866327e-05 4.99970565e-01 1.96035023e-05]
#############

In [60]:
data2 = {"x1": [0,0,1,1], "x2": [0,1,0,1], "y": [0,1,1,0]}
XOR = pd.DataFrame(data2)
XOR

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [61]:
X = XOR.drop("y", axis=1) # axis = 1 >>> dropping across column
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [62]:
y = XOR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  0

In [65]:
model = Perceptron(eta = 0.5, epochs=50)
model.fit(X,y)

self.weights: [-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 1
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 2
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 3
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 4
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 5
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 6
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 7
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 8
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 9
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 10
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 11
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 12
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 13
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 14
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 15
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 16
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 17
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 18
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 19
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 20
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 21
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 22
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 23
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 24
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 25
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 26
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 27
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 28
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 29
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 30
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 31
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 32
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 33
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 34
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 35
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 36
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 37
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 38
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 39
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 40
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 41
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 42
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 43
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 44
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 45
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 46
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 47
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

for epoch: 48
predicted value:
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:
[ 0.49993018  0.49996329 -0.99992946]
#############

for epoch: 49
predicted value:
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights:
[-6.98228869e-05 -3.67113602e-05  7.05355873e-05]
#############

In [68]:
model.predict(X)

array([0, 0, 0, 0])

#### Here we can see Perceptron can only classify the linear problem like AND, OR operation because they were linear problem. But in the case of XOR it couldn't classify correctly because it was a non-linear problem.